In [11]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report


In [2]:
data= pd.read_csv(r'D:\AI_ML_DL\Data&Python_code\DATA\CSV_file\Test_Data1.csv')
daf=pd.DataFrame(data)
#creating test-train data,
daf['is train']=np.random.uniform(0,1,len(daf))<=.75      
daf.head()

Class  A       B       C       D      E      F      G      H     I  ...  \
0     A  6  860.62  809.73  919.69  30.87  69.81  65.24  74.10  2.51  ...   
1     A  7  871.58  789.74  929.69  32.82  68.94  64.54  75.97  2.65  ...   
2     A  6  854.87  789.74  929.69  32.38  70.29  64.54  75.97  2.66  ...   
3     A  7  823.73  759.75  879.71  29.19  72.93  68.20  78.97  2.58  ...   
4     A  6  823.44  759.75  879.71  28.98  72.96  68.20  78.97  2.56  ...   

         Y6        Y7        Y8        Y9            Z1        Z2        Z4  \
0  0.002757 -0.003582  0.000125  0.001961 -3.290000e-08  0.000346  0.000956   
1  0.002757 -0.002944  0.000131  0.001932 -3.290000e-08  0.000358  0.000888   
2  0.003168 -0.002944  0.000125  0.001628 -3.290000e-08  0.000339  0.000875   
3  0.003168 -0.002490  0.000116  0.001572 -3.290000e-08  0.000308  0.000856   
4  0.003091 -0.002601  0.000126  0.001596 -3.290000e-08  0.000318  0.000913   

             Z5            Z6  is train  
0  9.150000e-07  1.190000e-07      True  
1  7.880000e-07  1.280000e-07      True  
2  7.660000e-07  1.150000e-07      True  
3  7.330000e-07  9.480000e-08      True  
4  8.330000e-07  1.010000e-07      True  

[5 rows x 43 columns]

In [3]:
# creating training, testing data
train, test= daf[daf["is train"]== True], daf[daf["is train"]==False]
print("test set:", len(test))
print("train set:", len(train))

test set: 1497
train set: 4342


In [4]:
Class=daf.columns[1:42] #finding the features
print(Class)

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
       'O', 'P', 'Q', 'R', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8',
       'X9', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'Y8', 'Y9', 'Z1', 'Z2',
       'Z4', 'Z5', 'Z6'],
      dtype='object')


In [5]:
y=pd.factorize(train['Class'])[0]
y1=pd.factorize(test['Class'])[0]

In [6]:
clf=RandomForestClassifier(n_jobs=2,random_state=0)
clf.fit(train[Class],y)

C:\Users\Banib\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [17]:
y_pred=clf.predict(test[Class]) # doing prediction
prediction=clf.predict_proba(test[Class])[0:10] # visualization of prediction in different way,individual probability for each class
print(prediction)
print(type(prediction),type(y1))

[[0.6 0.3 0.  0.  0.1 0. ]
 [0.4 0.2 0.2 0.  0.1 0.1]
 [0.2 0.4 0.3 0.1 0.  0. ]
 [0.4 0.2 0.4 0.  0.  0. ]
 [0.2 0.2 0.3 0.  0.1 0.2]
 [0.6 0.2 0.1 0.  0.1 0. ]
 [0.3 0.2 0.3 0.1 0.1 0. ]
 [0.4 0.2 0.3 0.  0.  0.1]
 [0.3 0.2 0.3 0.1 0.  0.1]
 [0.1 0.7 0.1 0.  0.1 0. ]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [18]:
# different way to find out confusion matrix

print(confusion_matrix(y1,y_pred))

[[174  53  33   0  12   8]
 [ 54 186  35   1  11   4]
 [ 25  50 345   1  13   2]
 [  4   3  11  27   5   9]
 [ 22  20  24   1 183   6]
 [ 15   5  14   3  16 122]]


In [19]:
print(classification_report(y1,y_pred))

              precision    recall  f1-score   support

           0       0.59      0.62      0.61       280
           1       0.59      0.64      0.61       291
           2       0.75      0.79      0.77       436
           3       0.82      0.46      0.59        59
           4       0.76      0.71      0.74       256
           5       0.81      0.70      0.75       175

    accuracy                           0.69      1497
   macro avg       0.72      0.65      0.68      1497
weighted avg       0.70      0.69      0.69      1497

